services:
  
  database:
    image: mysql:${MYSQL_VERSION}
    restart: on-failure
    ports:
      - 3306:3306
    env_file:
      - .env.staging
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env.staging
    depends_on:
      - database
    restart: on-failure

  # cron:
  #   image: mysql:8.0
  #   restart: on-failure
  #   depends_on:
  #     - app
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}