services:
  
  database:
    image: mysql:8.0
    restart: on-failure
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

  app:
    restart: on-failure
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - IQAIR_PROTOCOL=${IQAIR_PROTOCOL}
      - IQAIR_BASE_URL=${IQAIR_BASE_URL}
      - IQAIR_NEAREST_CITY_AQ_EP_PATH=${IQAIR_NEAREST_CITY_AQ_EP_PATH}
      - IQAIR_API_KEY=${IQAIR_API_KEY}

  # cron:
  #   image: mysql:8.0
  #   restart: on-failure
  #   depends_on:
  #     - app
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}